os:
  - osx
  - linux

language: node_js

node_js:
  - node
  - 10
  - 9
  - 8

cache: cargo

before_install:
  # Install Rust and Cargo
  - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
  - sh /tmp/rustup.sh -y --default-toolchain nightly
  - export PATH="$HOME/.cargo/bin:$PATH"
  - source "$HOME/.cargo/env"
  # Install NPM packages
  - node -v
  - npm -v
  - npm install

script:
  - ./ci/ci.sh
